### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Bean6754**
Replace 'cp' with 'dd' and ';' with '&&'.

### CODE REVIEW

**Comment by fiendish** [comment]
Reason why? The cp invocation comes from the debian.org faq.
https://www.debian.org/CD/faq/#write-usb

**Comment by fiendish** [comment]
@Bean6754 Can you comment on the reason for this PR?

**Comment by sethwoodworth** [comment]
The article on how [dd isn't a disk imaging tool](https://www.vidarholen.net/contents/blog/?p=479) is possibly why?
It's worth noting that the first command example the debian docs suggest is to `cp  <device>`

**Comment by fiendish** [comment]
The article is why *not* (since this page already suggests using cp). I think I'm just going to close this PR because it doesn't look like Bean6754 is coming back to explain any circumstances that require using dd. I'm happy to let it get reopened if someone comes back with an example where the cp invocation suggested by the debian docs fails.

**Comment by Bean6754** [comment]
So why would I use 'cp' or 'cat' over 'dd'? With 'dd' you can specify the block-size and display progress.

Could you also use 'rsync' or 'ftp' to copy an image across to a device?

I must know the advantages and disadvantages as this will be very useful for me.

**Comment by fiendish** [comment]
> So why would I use 'cp' ... over 'dd'?

Because you can, and because invocation of cp is simpler, and because to the best of my knowledge it "just works" without any fiddly arguments.

> With 'dd' you can specify the block-size

Specifying the block size is not a valuable feature for this task. It's super clumsy and requires the user to either know more than any user should ever need to know or to blindly follow some arcane copy/pasted thing they don't understand and that is probably wrong for their scenario only because dd chooses a bad size by default.

> display progress

Displaying progress could be useful, but then your PR doesn't even do that. Also dd's ability to report status is only relatively recent. If you want to see progress, you could use pv.

**Pull request closed without merging**
